#GoogleVis 1.1
```{r}
suppressPackageStartupMessages((library(googleVis)))
print(Fruits)
```
```{r}
M <- gvisMotionChart(Fruits, 'Fruit', 'Year',
                    option = list(width = 600, height = 400))
plot(M, 'chart')
```

```{r}
# Convert the Motion Chart to ggplot
library(ggplot2)
library(plotly)
# ggplot_chart <-gvis2ggplot(M)
```


```{r}
plot(M, file = 'test1.html')
```

# Convert the ggplot chart to an interactive plotly chart
plotly_chart <- ggplotly(ggplot_chart)

# Display the interactive plotly chart
plotly_chart


## Charts in googleVis
<center> "gvis + ChartType"
</center>

* Motion charts: `gvisMotionChart`
* Interactive maps: `gvisGeoChart`
* Interactive tables: `gvisTable`
* Line charts: `gvisLineChart`

#GvisGeo

```{r}
Exports
```


```{r}
G <- gvisGeoChart(Exports, locationvar = c('Country'),
                   colorvar = 'Profit',
                   options = list( width = 600, height = 400))
print(G)
```

## Specifying a region

```{r dependson='gv', resukts = 'asis', cache = TRUE}
G <- gvisGeoChart(Exports, locationvar = 'Country', 
                  colorvar = 'Profit', options = list(width = 600, height = 400, region = '150'))
plot(G, 'chart')
```

## Setting more options

```{r linechart, dependson='gv', results = 'asis', cache = T}

df <- data.frame(label = c('US', 'GB','BR'), val1 = c(1, 3, 4), val2 = c(23, 12, 32))

Line <- gvisLineChart(df, xvar = 'label', yvar = c('val1', 'val2'),
                      options = list(title = 'Hello World', legend = 'bottom',
                                     titleTextStyle = '{color: "red", fontSize: 18}',
                                     vaxis = '{gridlines:{color: "red", count: 3}}',
                                     haxis = '{title: "My label", titleTextStyle:{color: "blue"}}',
                                     series = '[{color: "green", targetAxisIndex: 0},
                                     {color: "blue", targetAxisIndex: 1}]',
                                     vaxes = '[{title:"Value 1 (%)", format = "##,######%"},
                                     {title: "Value 2 (\U00A3)"}]',
                                     curveType = 'function', width = 500, height = 300))

plot(Line)
```

## Combining multiple plots together

```{r multiplot, dependson='gv', results = 'asis', cache = T}
G <- gvisGeoChart(Exports, 'Country', 'Profit', options = list(width = 200, height = 100))
T1<- gvisTable(Exports, options = list(width = 200, height = 270)) 
M <- gvisMotionChart(Fruits, 'Fruit', 'Year', options = list(width = 400, height = 170)) 
GT <-gvisMerge(G, T1, horizontal = T)
GTM <- gvisMerge(GT, M, horizontal = T, tableOptions = 'bgcolor=\"#CCCCCC\'cellspacing = 10')
plot(GT)

```

```{r multiplot, dependson='gv', results = 'asis', cache = T}
plot(GTM)
print(GTM, 'chart')

```

```{r}
# library(knitr)
# spin('GoogleVis 1.1-1.2.R', knit = F)
# jupytext --to GoogleVis_1.1-1.2.ipynb GoogleVis_1.1-1.2.Rmd
```